// <auto-generated />
using System;
using BerryTestProject1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BerryTestProject1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250831155126_ResponseTableUpdate")]
    partial class ResponseTableUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BerryTestProject1.Models.PersonDetails", b =>
                {
                    b.Property<int>("PersonDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonDetailsId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("InteractionFrequency")
                        .HasColumnType("int");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearsKnown")
                        .HasColumnType("int");

                    b.HasKey("PersonDetailsId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonDetails");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Response", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<int>("PersonDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("StatementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ResponseId");

                    b.HasIndex("PersonDetailsId");

                    b.HasIndex("StatementId");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("BerryTestProject1.Models.ResultCategory", b =>
                {
                    b.Property<int>("ResultCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultCategoryId"));

                    b.Property<string>("CirclePlacement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ResultCategoryId");

                    b.ToTable("ResultCategory");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("FinalScore")
                        .HasColumnType("float");

                    b.Property<int>("PersonDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("ResultCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScoreId");

                    b.HasIndex("PersonDetailsId")
                        .IsUnique();

                    b.HasIndex("ResultCategoryId");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Statement", b =>
                {
                    b.Property<int>("StatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatementId"));

                    b.Property<string>("AssertiveStatement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StatementId");

                    b.ToTable("Statement");
                });

            modelBuilder.Entity("BerryTestProject1.Models.UserData", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("BerryTestProject1.Models.PersonDetails", b =>
                {
                    b.HasOne("BerryTestProject1.Models.UserData", "User")
                        .WithMany("PersonDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Response", b =>
                {
                    b.HasOne("BerryTestProject1.Models.PersonDetails", "PersonDetails")
                        .WithMany("Responses")
                        .HasForeignKey("PersonDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerryTestProject1.Models.Statement", "Statement")
                        .WithMany("Responses")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonDetails");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Score", b =>
                {
                    b.HasOne("BerryTestProject1.Models.PersonDetails", "PersonDetails")
                        .WithOne("Score")
                        .HasForeignKey("BerryTestProject1.Models.Score", "PersonDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerryTestProject1.Models.ResultCategory", "ResultCategory")
                        .WithMany("Scores")
                        .HasForeignKey("ResultCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonDetails");

                    b.Navigation("ResultCategory");
                });

            modelBuilder.Entity("BerryTestProject1.Models.PersonDetails", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("BerryTestProject1.Models.ResultCategory", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Statement", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("BerryTestProject1.Models.UserData", b =>
                {
                    b.Navigation("PersonDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
