// <auto-generated />
using System;
using BerryTestProject1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BerryTestProject1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250831145038_tablenameupdated")]
    partial class tablenameupdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BerryTestProject1.Models.PersonDetails", b =>
                {
                    b.Property<int>("PersonDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonDetailsId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("InteractionFrequency")
                        .HasColumnType("int");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearsKnown")
                        .HasColumnType("int");

                    b.HasKey("PersonDetailsId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonDetails");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Response", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<int>("PersonDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("StatementId")
                        .HasColumnType("int");

                    b.HasKey("ResponseId");

                    b.HasIndex("PersonDetailsId");

                    b.HasIndex("StatementId");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("BerryTestProject1.Models.ResultCategory", b =>
                {
                    b.Property<int>("ResultCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultCategoryId"));

                    b.Property<string>("CirclePlacement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ResultCategoryId");

                    b.ToTable("ResultCategory");

                    b.HasData(
                        new
                        {
                            ResultCategoryId = 1,
                            CirclePlacement = "The Core",
                            ColorCode = "blue",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 816, DateTimeKind.Local).AddTicks(6563),
                            Message = "Dear {user}, {name} is your heart and soul—an extraordinary, supportive companion. Never, ever leave or hurt {pronoun}.",
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 817, DateTimeKind.Local).AddTicks(9538)
                        },
                        new
                        {
                            ResultCategoryId = 2,
                            CirclePlacement = "The Inner Circle",
                            ColorCode = "teal",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(807),
                            Message = "{user}, {name} is your loyal friend—an honest companion with whom your secrets are safe. {pronoun} is your true partner in crime.",
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(810)
                        },
                        new
                        {
                            ResultCategoryId = 3,
                            CirclePlacement = "The Allies",
                            ColorCode = "white",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(813),
                            Message = "{name} is your supportive friend—a loyal and trusted companion. You may have temporary ego clashes, but the relationship is sustained with support and trust in the long run.",
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(814)
                        },
                        new
                        {
                            ResultCategoryId = 4,
                            CirclePlacement = "The Outer Circle",
                            ColorCode = "green",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(815),
                            Message = "{name} is neither your trusted friend nor your enemy. The communication is situation-based, not exclusive.",
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(815)
                        },
                        new
                        {
                            ResultCategoryId = 5,
                            CirclePlacement = "The Quarantine Zone",
                            ColorCode = "yellow",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(816),
                            Message = "You should probably limit your interaction with {name}. {pronoun} will drain your emotions for their own benefit.",
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(817)
                        },
                        new
                        {
                            ResultCategoryId = 6,
                            CirclePlacement = "The Exclusion Zone",
                            ColorCode = "red",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(818),
                            Message = "Dear {user}, you are in a toxic relationship. Back away from {name} immediately to protect your mental peace.",
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(818)
                        });
                });

            modelBuilder.Entity("BerryTestProject1.Models.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("FinalScore")
                        .HasColumnType("float");

                    b.Property<int>("PersonDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("ResultCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScoreId");

                    b.HasIndex("PersonDetailsId")
                        .IsUnique();

                    b.HasIndex("ResultCategoryId");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Statement", b =>
                {
                    b.Property<int>("StatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatementId"));

                    b.Property<string>("AssertiveStatement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StatementId");

                    b.ToTable("Statement");

                    b.HasData(
                        new
                        {
                            StatementId = 1,
                            AssertiveStatement = "{name} loves you unconditionally, enhances your mood, and makes you smile.",
                            Category = "WellWisher",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(7098),
                            Score = 5,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(7101)
                        },
                        new
                        {
                            StatementId = 2,
                            AssertiveStatement = "{name} encourages you to go beyond your limits and challenges you to grow.",
                            Category = "GrowthCatalyst",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8223),
                            Score = 4,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8225)
                        },
                        new
                        {
                            StatementId = 3,
                            AssertiveStatement = "You feel safe and comfortable sharing your worst secrets with {name}.",
                            Category = "Protector",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8228),
                            Score = 4,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8229)
                        },
                        new
                        {
                            StatementId = 4,
                            AssertiveStatement = "{name} will stand by you in tough times and encourages you to try new things.",
                            Category = "Supporter",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8230),
                            Score = 4,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8230)
                        },
                        new
                        {
                            StatementId = 5,
                            AssertiveStatement = "{name} calms your heart and mind, bringing you back to your senses when you are a mess.",
                            Category = "Stabilizer",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8231),
                            Score = 3,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8232)
                        },
                        new
                        {
                            StatementId = 6,
                            AssertiveStatement = "You automatically smile when you see {name}, and you share many happy memories together.",
                            Category = "JoyBringer",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8233),
                            Score = 3,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8233)
                        },
                        new
                        {
                            StatementId = 7,
                            AssertiveStatement = "The dislike from {name} feels irrational and baseless, more like a reflection of their own issues.",
                            Category = "Hater",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8234),
                            Score = -5,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8234)
                        },
                        new
                        {
                            StatementId = 8,
                            AssertiveStatement = "{name} has betrayed your trust or made you feel unimportant in your absence.",
                            Category = "Backstabber",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8235),
                            Score = -5,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8236)
                        },
                        new
                        {
                            StatementId = 9,
                            AssertiveStatement = "{name} twists facts to gain an emotional advantage over you.",
                            Category = "Manipulator",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8237),
                            Score = -4,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8237)
                        },
                        new
                        {
                            StatementId = 10,
                            AssertiveStatement = "{name} subtly chips away at your confidence with passive-aggressive remarks.",
                            Category = "Underminer",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8238),
                            Score = -4,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8239)
                        },
                        new
                        {
                            StatementId = 11,
                            AssertiveStatement = "You sense a lack of genuine joy from {name} when you share good news.",
                            Category = "Envyer",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8240),
                            Score = -3,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8240)
                        },
                        new
                        {
                            StatementId = 12,
                            AssertiveStatement = "{name} often exaggerates insignificant emotions to seek attention.",
                            Category = "DramaGenerator",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8242),
                            Score = -3,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8243)
                        },
                        new
                        {
                            StatementId = 13,
                            AssertiveStatement = "When you share a dream or goal, {name} encourages you to play small or stay safe.",
                            Category = "Stagnator",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8244),
                            Score = -3,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8244)
                        },
                        new
                        {
                            StatementId = 14,
                            AssertiveStatement = "{name} frequently uses your resources (time, money, energy) for their own benefit without gratitude.",
                            Category = "Leecher",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8287),
                            Score = -2,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8288)
                        },
                        new
                        {
                            StatementId = 15,
                            AssertiveStatement = "{name} seems to feed on your emotional insecurities, providing no real benefit to you.",
                            Category = "EmotionalVulture",
                            CreatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8289),
                            Score = -2,
                            UpdatedAt = new DateTime(2025, 8, 31, 20, 20, 36, 818, DateTimeKind.Local).AddTicks(8289)
                        });
                });

            modelBuilder.Entity("BerryTestProject1.Models.UserData", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("BerryTestProject1.Models.PersonDetails", b =>
                {
                    b.HasOne("BerryTestProject1.Models.UserData", "User")
                        .WithMany("PersonDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Response", b =>
                {
                    b.HasOne("BerryTestProject1.Models.PersonDetails", "PersonDetails")
                        .WithMany("Responses")
                        .HasForeignKey("PersonDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerryTestProject1.Models.Statement", "Statement")
                        .WithMany("Responses")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonDetails");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Score", b =>
                {
                    b.HasOne("BerryTestProject1.Models.PersonDetails", "PersonDetails")
                        .WithOne("Score")
                        .HasForeignKey("BerryTestProject1.Models.Score", "PersonDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerryTestProject1.Models.ResultCategory", "ResultCategory")
                        .WithMany("Scores")
                        .HasForeignKey("ResultCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonDetails");

                    b.Navigation("ResultCategory");
                });

            modelBuilder.Entity("BerryTestProject1.Models.PersonDetails", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("BerryTestProject1.Models.ResultCategory", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("BerryTestProject1.Models.Statement", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("BerryTestProject1.Models.UserData", b =>
                {
                    b.Navigation("PersonDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
